default: &default
  adapter: mysql2
  database: calender
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: 127.0.0.1
  port: 3306
  username: root
  password: password
  encoding: utf8

development:
  <<: *default

test:
  <<: *default